import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BookOpen, BrainCircuit, CheckCircle2, ChevronDown, Droplets, Leaf, Menu, ScanLine, Sprout, ThermometerSun, X } from 'lucide-react'

interface LandingPageProps { setIsAuthenticated: (value: boolean) => void }
const languages = [['en', 'EN'], ['am', 'አማ'], ['om', 'OM'], ['fr', 'FR'], ['ar', 'عربي'], ['es', 'ES']]

export default function LandingPage(_props: LandingPageProps) {
  const { t, i18n } = useTranslation()
  const navigate = useNavigate()
  const [menuOpen, setMenuOpen] = useState(false)
  const changeLanguage = (language: string) => { void i18n.changeLanguage(language); localStorage.setItem('agro_lang', language); setMenuOpen(false) }
  const featureItems = [[ScanLine, t('landing.featureAI'), t('landing.featureAIDesc')], [BarChart3, t('landing.featureAnalytics'), t('landing.featureAnalyticsDesc')], [BookOpen, t('landing.featureEducation'), t('landing.featureEducationDesc')], [ThermometerSun, t('tools.soilAnalysis'), t('tools.soilAnalysisDesc')], [Droplets, t('tools.irrigationPrediction'), t('tools.irrigationPredictionDesc')], [Sprout, t('tools.yieldPrediction'), t('tools.yieldPredictionDesc')]] as const
  const workflow = [[ScanLine, t('landingPremium.cropImage')], [BrainCircuit, t('landingPremium.aiAnalysis')], [CheckCircle2, t('landingPremium.diseaseDetection')], [ThermometerSun, t('landingPremium.soilIntelligence')], [Droplets, t('landingPremium.irrigationPlan')], [BarChart3, t('landingPremium.yieldPrediction')]] as const
  const publicLinks = [['#home', t('landingPremium.home')], ['#features', t('landing.features')], ['/ai-chat', t('nav.aiChat')], ['/academy', t('nav.academy')], ['/dashboard', t('nav.dashboard')], ['/tools', t('nav.tools')]]

  return <div className="landing-page" id="home">
    <div className="landing-grid" aria-hidden="true" />
    <header className="landing-nav">
      <Link to="/" className="landing-brand" aria-label="AgroVision AI home"><span className="landing-brand-mark"><Leaf size={20} /></span><span>AgroVision <b>AI</b></span></Link>
      <nav className={`landing-links ${menuOpen ? 'is-open' : ''}`} aria-label="Main navigation">{publicLinks.map(([href, label]) => <Link key={href} to={href}>{label}</Link>)}<div className="landing-mobile-actions"><Link className="landing-login" to="/login">{t('auth.login')}</Link><button className="landing-button landing-button-small" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={15} /></button></div></nav>
      <div className="landing-nav-actions"><label className="sr-only" htmlFor="landing-language">Language</label><div className="landing-select-wrap"><select id="landing-language" value={i18n.language} onChange={(event) => changeLanguage(event.target.value)}>{languages.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><ChevronDown size={14} aria-hidden="true" /></div><Link className="landing-login" to="/login">{t('auth.login')}</Link><button className="landing-button landing-button-small landing-desktop-cta" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={15} /></button><button className="landing-menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label="Toggle navigation menu" aria-expanded={menuOpen}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>
    </header>
    <main>
      <section className="landing-hero landing-container"><div className="landing-hero-copy"><div className="landing-eyebrow"><span />{t('landingPremium.aiPoweredAgriculture')}</div><h1>{t('landing.hero')}</h1><p>{t('landing.heroDesc')}</p><div className="landing-hero-actions"><button className="landing-button" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={18} /></button><Link className="landing-text-link" to="/ai-chat">{t('landingPremium.exploreAI')} <ArrowDownRight size={17} /></Link></div><div className="landing-proof"><span className="landing-proof-avatars"><i /><i /><i /></span><span>{t('landingPremium.builtForDecisions')}</span><span className="landing-proof-line" /></div></div><div className="landing-hero-visual"><div className="landing-photo-frame"><img src="/front.png" alt={t('landingPremium.heroImageAlt')} /><div className="landing-photo-shade" /></div><div className="landing-visual-label"><span className="landing-live-dot" />{t('landingPremium.liveFieldIntelligence')} <strong>●</strong></div><div className="landing-float-card landing-float-disease"><span className="landing-card-icon danger"><ScanLine size={16} /></span><span><b>{t('landingPremium.diseaseDetected')}</b><small>{t('landingPremium.leafHealthConfidence')}</small></span><CheckCircle2 className="landing-card-check" size={17} /></div><div className="landing-float-card landing-float-soil"><span className="landing-card-icon blue"><Droplets size={16} /></span><span><b>{t('landingPremium.soilMoisture')}</b><small>{t('landingPremium.optimalMoisture')}</small></span><span className="landing-signal">↗</span></div><div className="landing-float-card landing-float-yield"><span className="landing-card-icon green"><BarChart3 size={16} /></span><span><b>{t('landingPremium.yieldPrediction')}</b><small>{t('landingPremium.yieldSeason')}</small></span></div></div></section>
      <section className="landing-metrics landing-container" aria-label={t('landingPremium.metricsLabel')}>{[['38+', t('landingPremium.cropClasses')], ['6', t('landingPremium.languages')], ['20', t('landingPremium.agricultureCourses')], ['500', t('landingPremium.lessons')]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section className="landing-section landing-container" id="features"><div className="landing-section-heading"><div><div className="landing-kicker">{t('landingPremium.connectedIntelligence')}</div><h2>{t('landingPremium.everythingFarmNeeds')}<br /><em>{t('landingPremium.toMoveForward')}</em></h2></div><p>{t('landingPremium.featureIntro')}</p></div><div className="landing-feature-grid">{featureItems.map(([Icon, title, description], index) => <article className="landing-feature-card" key={title}><span className={`landing-feature-number n-${index + 1}`}>0{index + 1}</span><span className="landing-feature-icon"><Icon size={21} /></span><h3>{title}</h3><p>{description}</p><ArrowUpRight size={18} className="landing-feature-arrow" /></article>)}</div></section>
      <section className="landing-story landing-container"><div className="landing-story-copy"><div className="landing-kicker">{t('landingPremium.agrovisionLoop')}</div><h2>{t('landingPremium.fromDataTo')} <em>{t('landingPremium.healthierHarvest')}</em></h2><p>{t('landingPremium.workflowIntro')}</p><Link className="landing-text-link" to="/dashboard">{t('landingPremium.seeFarmIntelligence')} <ArrowRight size={17} /></Link></div><div className="landing-workflow" aria-label={t('landingPremium.workflowLabel')}>{workflow.map(([Icon, label], index) => <div className="landing-workflow-item" key={label}><div className="landing-workflow-node"><Icon size={18} /></div><span>{label}</span>{index < workflow.length - 1 && <ArrowRight className="landing-workflow-arrow" size={16} />}</div>)}<div className="landing-harvest"><Sprout size={20} /><span>{t('landingPremium.healthierHarvest')}</span></div></div></section>
      <section className="landing-cta landing-container"><div><div className="landing-kicker">{t('landingPremium.readyWhenFieldsAre')}</div><h2>{t('landingPremium.makeEveryDecision')}<br /><em>{t('landingPremium.count')}</em></h2></div><div><p>{t('ui.smartAgriculture')}</p><div className="landing-hero-actions"><button className="landing-button" onClick={() => navigate('/signup')}>{t('landingPremium.startFarmingSmarter')} <ArrowRight size={18} /></button><Link className="landing-text-link light" to="/tools">{t('landingPremium.exploreAITools')} <ArrowRight size={17} /></Link></div></div></section>
    </main>
  </div>
}
