import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BookOpen, BrainCircuit, CheckCircle2, ChevronDown, Droplets, Leaf, Menu, ScanLine, Sprout, ThermometerSun, X } from 'lucide-react'

interface LandingPageProps { setIsAuthenticated: (value: boolean) => void }
const languages = [['en', 'EN'], ['am', 'አማ'], ['om', 'OM'], ['fr', 'FR'], ['ar', 'عربي'], ['es', 'ES']]

export default function LandingPage(_props: LandingPageProps) {
  const { t, i18n } = useTranslation()
  const navigate = useNavigate()
  const [menuOpen, setMenuOpen] = useState(false)
  const changeLanguage = (language: string) => { void i18n.changeLanguage(language); localStorage.setItem('agro_lang', language); setMenuOpen(false) }
  const featureItems = [[ScanLine, t('landing.featureAI'), t('landing.featureAIDesc')], [BarChart3, t('landing.featureAnalytics'), t('landing.featureAnalyticsDesc')], [BookOpen, t('landing.featureEducation'), t('landing.featureEducationDesc')], [ThermometerSun, t('tools.soilAnalysis'), t('tools.soilAnalysisDesc')], [Droplets, t('tools.irrigationPrediction'), t('tools.irrigationPredictionDesc')], [Sprout, t('tools.yieldPrediction'), t('tools.yieldPredictionDesc')]] as const
  const workflow = [[ScanLine, 'Crop image'], [BrainCircuit, 'AI analysis'], [CheckCircle2, 'Disease detection'], [ThermometerSun, 'Soil intelligence'], [Droplets, 'Irrigation plan'], [BarChart3, 'Yield prediction']] as const
  const publicLinks = [['#home', 'Home'], ['#features', t('landing.features')], ['/ai-chat', t('nav.aiChat')], ['/academy', t('nav.academy')], ['/dashboard', t('nav.dashboard')], ['/tools', t('nav.tools')]]

  return <div className="landing-page" id="home">
    <div className="landing-grid" aria-hidden="true" />
    <header className="landing-nav">
      <Link to="/" className="landing-brand" aria-label="AgroVision AI home"><span className="landing-brand-mark"><Leaf size={20} /></span><span>AgroVision <b>AI</b></span></Link>
      <nav className={`landing-links ${menuOpen ? 'is-open' : ''}`} aria-label="Main navigation">{publicLinks.map(([href, label]) => <Link key={href} to={href}>{label}</Link>)}<div className="landing-mobile-actions"><Link className="landing-login" to="/login">{t('auth.login')}</Link><button className="landing-button landing-button-small" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={15} /></button></div></nav>
      <div className="landing-nav-actions"><label className="sr-only" htmlFor="landing-language">Language</label><div className="landing-select-wrap"><select id="landing-language" value={i18n.language} onChange={(event) => changeLanguage(event.target.value)}>{languages.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><ChevronDown size={14} aria-hidden="true" /></div><Link className="landing-login" to="/login">{t('auth.login')}</Link><button className="landing-button landing-button-small landing-desktop-cta" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={15} /></button><button className="landing-menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label="Toggle navigation menu" aria-expanded={menuOpen}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>
    </header>
    <main>
      <section className="landing-hero landing-container"><div className="landing-hero-copy"><div className="landing-eyebrow"><span />AI-powered agriculture</div><h1>{t('landing.hero')}</h1><p>{t('landing.heroDesc')}</p><div className="landing-hero-actions"><button className="landing-button" onClick={() => navigate('/signup')}>{t('landing.getStarted')} <ArrowRight size={18} /></button><Link className="landing-text-link" to="/ai-chat">Explore AI <ArrowDownRight size={17} /></Link></div><div className="landing-proof"><span className="landing-proof-avatars"><i /><i /><i /></span><span>Built for decisions in the field</span><span className="landing-proof-line" /></div></div><div className="landing-hero-visual"><div className="landing-photo-frame"><img src="/front.png" alt="Farmer using AI crop intelligence in a corn field" /><div className="landing-photo-shade" /></div><div className="landing-visual-label"><span className="landing-live-dot" />Live field intelligence <strong>●</strong></div><div className="landing-float-card landing-float-disease"><span className="landing-card-icon danger"><ScanLine size={16} /></span><span><b>Disease detected</b><small>Leaf health · 94% confidence</small></span><CheckCircle2 className="landing-card-check" size={17} /></div><div className="landing-float-card landing-float-soil"><span className="landing-card-icon blue"><Droplets size={16} /></span><span><b>Soil moisture</b><small>Optimal · 68%</small></span><span className="landing-signal">↗</span></div><div className="landing-float-card landing-float-yield"><span className="landing-card-icon green"><BarChart3 size={16} /></span><span><b>Yield prediction</b><small>+18.4% this season</small></span></div></div></section>
      <section className="landing-metrics landing-container" aria-label="AgroVision metrics">{[['38+', 'AI crop classes'], ['6', 'Languages'], ['20', 'Agriculture courses'], ['500', 'Lessons']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section className="landing-section landing-container" id="features"><div className="landing-section-heading"><div><div className="landing-kicker">One connected intelligence layer</div><h2>Everything your farm needs<br /><em>to move forward.</em></h2></div><p>From the first crop image to the final harvest, turn complex field signals into clear, confident action.</p></div><div className="landing-feature-grid">{featureItems.map(([Icon, title, description], index) => <article className="landing-feature-card" key={title}><span className={`landing-feature-number n-${index + 1}`}>0{index + 1}</span><span className="landing-feature-icon"><Icon size={21} /></span><h3>{title}</h3><p>{description}</p><ArrowUpRight size={18} className="landing-feature-arrow" /></article>)}</div></section>
      <section className="landing-story landing-container"><div className="landing-story-copy"><div className="landing-kicker">The AgroVision loop</div><h2>From data to a <em>healthier harvest.</em></h2><p>Every signal becomes a practical next step. AgroVision brings your farm&apos;s most important decisions into focus.</p><Link className="landing-text-link" to="/dashboard">See your farm intelligence <ArrowRight size={17} /></Link></div><div className="landing-workflow" aria-label="Farm intelligence workflow">{workflow.map(([Icon, label], index) => <div className="landing-workflow-item" key={label}><div className="landing-workflow-node"><Icon size={18} /></div><span>{label}</span>{index < workflow.length - 1 && <ArrowRight className="landing-workflow-arrow" size={16} />}</div>)}<div className="landing-harvest"><Sprout size={20} /><span>Healthier harvest</span></div></div></section>
      <section className="landing-cta landing-container"><div><div className="landing-kicker">Ready when your fields are</div><h2>Make every decision<br /><em>count.</em></h2></div><div><p>{t('ui.smartAgriculture')}</p><div className="landing-hero-actions"><button className="landing-button" onClick={() => navigate('/signup')}>Start farming smarter <ArrowRight size={18} /></button><Link className="landing-text-link light" to="/tools">Explore AI tools <ArrowRight size={17} /></Link></div></div></section>
    </main>
  </div>
}
